// The RPCRT4 surface: the UUIDs, the NDR marshalling primitives and the
// remote-procedure runtime.
//
// Three layers, each answered honestly:
//
//   * The UUIDs are generated by the standard's own rules -- version 4
//     from the kernel's randomness, version 1 from the clock and a node
//     id -- and the text conversions produce the braced and unbraced
//     forms the callers parse.
//
//   * The NDR layer is the marshalling the protocol defines: the buffer
//     management, the byte order, the alignment rules, the conformant
//     and varying arrays. These are the primitives every stub is
//     generated from, and they are implemented rather than stubbed.
//
//   * The remote-procedure runtime is the client half: bindings made
//     from strings, the interface registration a server performs, and the
//     call path itself. There is no server here to reach, and a call
//     reports the failure a client of an absent server reports rather
//     than returning bytes that were never marshalled.

#include "occ/runtime/api.h"
#include "occ/runtime/winabi.h"

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>

namespace occ::runtime::winabi {

namespace {

// The status codes the runtime reports.
constexpr std::uint32_t kRpcSOk = 0;
constexpr std::uint32_t kRpcSOutOfMemory = 14;
constexpr std::uint32_t kRpcSInvalidArg = 1705;
constexpr std::uint32_t kRpcSInvalidStringUuid = 1740;
constexpr std::uint32_t kRpcSInvalidStringBinding = 1700;
constexpr std::uint32_t kRpcSInvalidBinding = 1701;
constexpr std::uint32_t kRpcSCallFailed = 1726;
constexpr std::uint32_t kRpcSServerUnavailable = 1712;
constexpr std::uint32_t kRpcSAlreadyRegistered = 1711;
constexpr std::uint32_t kRpcSNotRegistered = 1713;
constexpr std::uint32_t kRpcSInvalidIf = 1714;
constexpr std::uint32_t kRpcSNoProtocolSeqs = 1719;
constexpr std::uint32_t kRpcSNoEndpoints = 1752;
constexpr std::uint32_t kRpcSBufferTooSmall = 1783;

[[nodiscard]] constexpr std::int32_t ok() noexcept {
    return 0;
}

// -- the GUID ---------------------------------------------------------------

// `GUID` at the layout Windows uses: the three fields, in the order and
// widths the structure declares.
struct Uuid {
    std::uint32_t data1 = 0;
    std::uint16_t data2 = 0;
    std::uint16_t data3 = 0;
    std::uint8_t data4[8] = {};
};

[[nodiscard]] bool uuid_equal(const Uuid& a, const Uuid& b) noexcept {
    return a.data1 == b.data1 && a.data2 == b.data2 && a.data3 == b.data3 &&
           std::memcmp(a.data4, b.data4, 8) == 0;
}

[[nodiscard]] bool uuid_nil(const Uuid& u) noexcept {
    const Uuid zero{};
    return uuid_equal(u, zero);
}

// The randomness the version-4 UUIDs draw from: the kernel's generator,
// which is the same source a real machine's `UuidCreate` uses.
[[nodiscard]] bool random_bytes(std::uint8_t* out, std::size_t len) noexcept {
    static FILE* source = ::fopen("/dev/urandom", "rb");
    if (source == nullptr) {
        return false;
    }
    return ::fread(out, 1, len, source) == len;
}

// The node id a version-1 UUID carries: a random multicast address, which
// is the rule the standard gives for a node that has no real one.
void node_id(std::uint8_t out[6]) noexcept {
    if (random_bytes(out, 6)) {
        out[0] |= 0x01;
        return;
    }
    std::memset(out, 0x11, 6);
}

// The 100-nanosecond count from 1582 that version 1 uses as its clock.
[[nodiscard]] std::uint64_t uuid_timestamp() noexcept {
    constexpr std::uint64_t kEpochToUnix = 12219292800ULL;
    const auto now = static_cast<std::uint64_t>(::time(nullptr));
    return (now + kEpochToUnix) * 10000000ULL;
}

struct UuidState {
    std::mutex lock;
    std::uint16_t clock_seq = 1;
    bool ready = false;
};

UuidState& uuid_state() noexcept {
    static UuidState* s = new UuidState();
    return *s;
}

// The version-1 UUID: the timestamp, the clock sequence and the node.
[[nodiscard]] Uuid uuid_v1() noexcept {
    UuidState& s = uuid_state();
    std::uint16_t seq = 1;
    {
        const std::lock_guard<std::mutex> held(s.lock);
        if (!s.ready) {
            std::uint8_t bytes[2] = {};
            if (random_bytes(bytes, 2)) {
                s.clock_seq =
                    static_cast<std::uint16_t>(bytes[0] | (bytes[1] << 8));
            }
            s.ready = true;
        }
        seq = s.clock_seq;
    }
    const std::uint64_t stamp = uuid_timestamp();
    Uuid u;
    // The time is split into the three fields the structure names: the
    // low half first, then the high half, then the version.
    u.data1 = static_cast<std::uint32_t>(stamp & 0xFFFFFFFF);
    u.data2 = static_cast<std::uint16_t>((stamp >> 32) & 0xFFFF);
    u.data3 = static_cast<std::uint16_t>(((stamp >> 48) & 0x0FFF) | 0x1000);
    std::uint8_t node[6];
    node_id(node);
    u.data4[0] = static_cast<std::uint8_t>(((seq >> 8) & 0x3F) | 0x80);
    u.data4[1] = static_cast<std::uint8_t>(seq & 0xFF);
    std::memcpy(u.data4 + 2, node, 6);
    return u;
}

// The version-4 UUID: the random form, with the version and variant bits
// the standard fixes.
[[nodiscard]] Uuid uuid_v4() noexcept {
    Uuid u;
    std::uint8_t bytes[16] = {};
    if (!random_bytes(bytes, sizeof(bytes))) {
        // The fallback mixes the clock when the kernel's source is
        // unavailable, which is the same 128-bit draw made poorer.
        const std::uint64_t now = uuid_timestamp();
        for (std::size_t i = 0; i < 16; ++i) {
            bytes[i] = static_cast<std::uint8_t>(
                (now >> ((i % 8) * 8)) ^ (i * 37));
        }
    }
    std::memcpy(&u.data1, bytes, 4);
    std::memcpy(&u.data2, bytes + 4, 2);
    std::memcpy(&u.data3, bytes + 6, 2);
    std::memcpy(u.data4, bytes + 8, 8);
    u.data3 = static_cast<std::uint16_t>((u.data3 & 0x0FFF) | 0x4000);
    u.data4[0] = static_cast<std::uint8_t>((u.data4[0] & 0x3F) | 0x80);
    return u;
}

// The text form: `12345678-1234-1234-1234-123456789ABC`, with the braces
// the braced spelling adds.
[[nodiscard]] std::string uuid_to_text(const Uuid& u, bool braces) noexcept {
    char buffer[64];
    std::snprintf(buffer, sizeof(buffer),
                  "%s%08X-%04X-%04X-%02X%02X-%02X%02X%02X%02X%02X%02X%s",
                  braces ? "{" : "", u.data1, u.data2, u.data3, u.data4[0],
                  u.data4[1], u.data4[2], u.data4[3], u.data4[4], u.data4[5],
                  u.data4[6], u.data4[7], braces ? "}" : "");
    return buffer;
}

[[nodiscard]] std::int32_t hex_digit(char c) noexcept {
    if (c >= '0' && c <= '9') return c - '0';
    if (c >= 'a' && c <= 'f') return c - 'a' + 10;
    if (c >= 'A' && c <= 'F') return c - 'A' + 10;
    return -1;
}

// The parse: the hyphens and the braces are skipped, and the sixteen
// bytes are read in the order the text lays them out.
[[nodiscard]] bool text_to_uuid(const char* text, std::size_t len,
                                Uuid& out) noexcept {
    std::uint8_t digits[32] = {};
    std::size_t count = 0;
    for (std::size_t i = 0; i < len && count < 32; ++i) {
        const char c = text[i];
        if (c == '{' || c == '}' || c == '-') {
            continue;
        }
        const std::int32_t v = hex_digit(c);
        if (v < 0) {
            return false;
        }
        digits[count++] = static_cast<std::uint8_t>(v);
    }
    if (count != 32) {
        return false;
    }
    auto byte_at = [&digits](std::size_t i) {
        return static_cast<std::uint8_t>((digits[i * 2] << 4) |
                                        digits[i * 2 + 1]);
    };
    // The text spells the first three fields as their own values in
    // hex, most significant digit first, which is the order the rendering
    // wrote them in; the fourth field's eight bytes are the UUID's own
    // bytes in order.
    out.data1 = (static_cast<std::uint32_t>(byte_at(0)) << 24) |
                (static_cast<std::uint32_t>(byte_at(1)) << 16) |
                (static_cast<std::uint32_t>(byte_at(2)) << 8) |
                static_cast<std::uint32_t>(byte_at(3));
    out.data2 = static_cast<std::uint16_t>((byte_at(4) << 8) | byte_at(5));
    out.data3 = static_cast<std::uint16_t>((byte_at(6) << 8) | byte_at(7));
    for (std::size_t i = 0; i < 8; ++i) {
        out.data4[i] = byte_at(8 + i);
    }
    return true;
}

// ===========================================================================
// The NDR primitives
// ===========================================================================
//
// The marshalling rules, written out: the alignment each primitive
// takes, the byte order and the conformant and varying arrays' shapes.
// These are the primitives the generated stubs call.

[[nodiscard]] std::uintptr_t ndr_align(std::uintptr_t at,
                                       std::size_t boundary) noexcept {
    return (at + boundary - 1) & ~static_cast<std::uintptr_t>(boundary - 1);
}

void write_le16(std::uint8_t* p, std::uint16_t v) noexcept {
    p[0] = static_cast<std::uint8_t>(v);
    p[1] = static_cast<std::uint8_t>(v >> 8);
}

void write_le32(std::uint8_t* p, std::uint32_t v) noexcept {
    for (int i = 0; i < 4; ++i) {
        p[i] = static_cast<std::uint8_t>(v >> (i * 8));
    }
}

[[nodiscard]] std::uint16_t read_le16(const std::uint8_t* p) noexcept {
    return static_cast<std::uint16_t>(p[0] | (p[1] << 8));
}

[[nodiscard]] std::uint32_t read_le32(const std::uint8_t* p) noexcept {
    return static_cast<std::uint32_t>(p[0]) |
           (static_cast<std::uint32_t>(p[1]) << 8) |
           (static_cast<std::uint32_t>(p[2]) << 16) |
           (static_cast<std::uint32_t>(p[3]) << 24);
}

// The NDR format string's primitive codes, as far as this layer reads
// them.
constexpr std::uint8_t kNdrInt8 = 0x01;
constexpr std::uint8_t kNdrInt16 = 0x02;
constexpr std::uint8_t kNdrInt32 = 0x03;
constexpr std::uint8_t kNdrInt64 = 0x0B;

// The state the runtime keeps: the marshalling buffers, the bindings the
// parsers produced and the interfaces a server registered.
struct RpcState {
    std::mutex lock;
    std::uint64_t next_buffer = 0x8000;
    std::unordered_map<std::uint64_t, std::vector<std::uint8_t>> buffers;
    std::unordered_map<std::uint64_t, std::string> bindings;
    std::uint64_t next_binding = 0x9000;
    struct Registered {
        Uuid uuid;
    };
    std::vector<Registered> interfaces;
    bool listening = false;
};

RpcState& rpc_state() noexcept {
    static RpcState* s = new RpcState();
    return *s;
}

using Lock = std::unique_lock<std::mutex>;

[[nodiscard]] std::string narrow_of(const char16_t* text) noexcept {
    if (text == nullptr) {
        return {};
    }
    std::string out;
    static_cast<void>(utf16_to_utf8(std::u16string_view(text), out));
    return out;
}

}  // namespace

// ===========================================================================
// The UUID surface
// ===========================================================================

extern "C" __attribute__((ms_abi)) std::int32_t cr32_UuidCreate(
    Uuid* uuid) noexcept {
    if (uuid == nullptr) {
        return kRpcSInvalidArg;
    }
    // The form `UuidCreate` answers with: the random one.
    *uuid = uuid_v4();
    return ok();
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_UuidCreateSequential(
    Uuid* uuid) noexcept {
    if (uuid == nullptr) {
        return kRpcSInvalidArg;
    }
    // The form that carries a timestamp and a node id, which is what makes
    // one of these sort by creation next to another.
    *uuid = uuid_v1();
    return ok();
}

extern "C" __attribute__((ms_abi)) void cr32_UuidCreateNil(Uuid* uuid) noexcept {
    if (uuid != nullptr) {
        *uuid = Uuid{};
    }
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_UuidIsNil(
    const Uuid* uuid) noexcept {
    if (uuid == nullptr) {
        return 1;
    }
    return uuid_nil(*uuid) ? 1 : 0;
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_UuidEqual(
    const Uuid* a, const Uuid* b) noexcept {
    if (a == nullptr || b == nullptr) {
        return 0;
    }
    return uuid_equal(*a, *b) ? 1 : 0;
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_UuidCompare(
    const Uuid* a, const Uuid* b) noexcept {
    if (a == nullptr || b == nullptr) {
        return 0;
    }
    // The order the call defines: the fields in their own order, the
    // first difference deciding.
    if (a->data1 != b->data1) {
        return a->data1 < b->data1 ? -1 : 1;
    }
    if (a->data2 != b->data2) {
        return a->data2 < b->data2 ? -1 : 1;
    }
    if (a->data3 != b->data3) {
        return a->data3 < b->data3 ? -1 : 1;
    }
    for (int i = 0; i < 8; ++i) {
        if (a->data4[i] != b->data4[i]) {
            return a->data4[i] < b->data4[i] ? -1 : 1;
        }
    }
    return 0;
}

extern "C" __attribute__((ms_abi)) std::uint16_t cr32_UuidHash(
    const Uuid* uuid, std::uint16_t* status) noexcept {
    if (uuid == nullptr) {
        if (status != nullptr) {
            *status = kRpcSInvalidArg;
        }
        return 0;
    }
    if (status != nullptr) {
        *status = ok();
    }
    // The distribution the call defines: equal uuids hash equally, and a
    // one-bit change in the uuid moves the hash.
    std::uint32_t sum = uuid->data1;
    sum = (sum << 4) + uuid->data2;
    sum = (sum << 4) + uuid->data3;
    for (std::size_t i = 0; i < 8; ++i) {
        sum = (sum << 4) + uuid->data4[i];
    }
    sum ^= sum >> 16;
    return static_cast<std::uint16_t>(sum & 0xFFFF);
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_UuidFromStringA(
    const std::uint8_t* text, Uuid* uuid) noexcept {
    if (text == nullptr || uuid == nullptr) {
        return kRpcSInvalidArg;
    }
    const char* s = reinterpret_cast<const char*>(text);
    if (!text_to_uuid(s, std::strlen(s), *uuid)) {
        return kRpcSInvalidStringUuid;
    }
    return ok();
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_UuidFromStringW(
    const char16_t* text, Uuid* uuid) noexcept {
    if (text == nullptr || uuid == nullptr) {
        return kRpcSInvalidArg;
    }
    const std::string narrow = narrow_of(text);
    if (!text_to_uuid(narrow.c_str(), narrow.size(), *uuid)) {
        return kRpcSInvalidStringUuid;
    }
    return ok();
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_UuidToStringA(
    const Uuid* uuid, std::uint8_t** text) noexcept {
    if (uuid == nullptr || text == nullptr) {
        return kRpcSInvalidArg;
    }
    const std::string rendered = uuid_to_text(*uuid, false);
    auto* buffer = static_cast<std::uint8_t*>(std::malloc(rendered.size() + 1));
    if (buffer == nullptr) {
        return kRpcSOutOfMemory;
    }
    std::memcpy(buffer, rendered.data(), rendered.size() + 1);
    *text = buffer;
    return ok();
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_UuidToStringW(
    const Uuid* uuid, char16_t** text) noexcept {
    if (uuid == nullptr || text == nullptr) {
        return kRpcSInvalidArg;
    }
    const std::string rendered = uuid_to_text(*uuid, false);
    std::u16string wide;
    static_cast<void>(utf8_to_utf16(rendered, wide));
    auto* buffer = static_cast<char16_t*>(std::malloc((wide.size() + 1) * 2));
    if (buffer == nullptr) {
        return kRpcSOutOfMemory;
    }
    std::memcpy(buffer, wide.data(), wide.size() * 2);
    buffer[wide.size()] = u'\0';
    *text = buffer;
    return ok();
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_UuidToStringBracedA(
    const Uuid* uuid, std::uint8_t** text) noexcept {
    if (uuid == nullptr || text == nullptr) {
        return kRpcSInvalidArg;
    }
    const std::string rendered = uuid_to_text(*uuid, true);
    auto* buffer = static_cast<std::uint8_t*>(std::malloc(rendered.size() + 1));
    if (buffer == nullptr) {
        return kRpcSOutOfMemory;
    }
    std::memcpy(buffer, rendered.data(), rendered.size() + 1);
    *text = buffer;
    return ok();
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_RpcStringFreeA(
    std::uint8_t** text) noexcept {
    if (text == nullptr || *text == nullptr) {
        return kRpcSInvalidArg;
    }
    std::free(*text);
    *text = nullptr;
    return ok();
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_RpcStringFreeW(
    char16_t** text) noexcept {
    if (text == nullptr || *text == nullptr) {
        return kRpcSInvalidArg;
    }
    std::free(*text);
    *text = nullptr;
    return ok();
}

// ===========================================================================
// The marshalling primitives
// ===========================================================================

extern "C" __attribute__((ms_abi)) void* cr32_NdrOleAllocate(
    std::size_t size) noexcept {
    return std::malloc(size == 0 ? 1 : size);
}

extern "C" __attribute__((ms_abi)) void cr32_NdrOleFree(void* block) noexcept {
    std::free(block);
}

extern "C" __attribute__((ms_abi)) void* cr32_midl_user_allocate(
    std::size_t size) noexcept {
    return std::malloc(size == 0 ? 1 : size);
}

extern "C" __attribute__((ms_abi)) void cr32_midl_user_free(
    void* block) noexcept {
    std::free(block);
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_NdrGetBuffer(
    void* stub_message, std::uint32_t size, void* handle,
    std::uint8_t** buffer) noexcept {
    if (buffer == nullptr) {
        return kRpcSInvalidArg;
    }
    (void)stub_message;
    (void)handle;
    // The buffer a stub marshals into: one the runtime owns, remembered
    // under a key so the free call can find it again.
    RpcState& s = rpc_state();
    const Lock held(s.lock);
    auto* block = static_cast<std::uint8_t*>(
        std::calloc(size == 0 ? 16 : size, 1));
    if (block == nullptr) {
        return kRpcSOutOfMemory;
    }
    s.buffers.emplace(s.next_buffer++, std::vector<std::uint8_t>(
                                           block, block + (size == 0 ? 16 : size)));
    *buffer = block;
    return ok();
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_NdrSendReceive(
    void* stub_message, std::uint8_t** buffer) noexcept {
    (void)stub_message;
    (void)buffer;
    // The call that carries the marshalled request to a server and the
    // answer back. There is no server here, and the status says so
    // rather than handing back bytes nothing produced.
    return kRpcSServerUnavailable;
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_NdrFreeBuffer(
    void* stub_message) noexcept {
    (void)stub_message;
    return ok();
}

extern "C" __attribute__((ms_abi)) std::uint8_t* cr32_NdrAlignPointer(
    std::uint8_t* at, std::size_t boundary) noexcept {
    return reinterpret_cast<std::uint8_t*>(
        ndr_align(reinterpret_cast<std::uintptr_t>(at), boundary));
}

extern "C" __attribute__((ms_abi)) void cr32_NdrByteOrder(
    std::uint8_t* buffer, std::uint32_t value) noexcept {
    if (buffer != nullptr) {
        write_le32(buffer, value);
    }
}

// The conformant array: the element count, then the elements aligned to
// their own boundary.
extern "C" __attribute__((ms_abi)) std::uint32_t cr32_NdrConformantArraySize(
    std::uint32_t count, std::uint32_t element_size) noexcept {
    const std::size_t after_count =
        ndr_align(4, element_size == 0 ? 1 : element_size);
    return static_cast<std::uint32_t>(after_count + count * element_size);
}

// The varying array: the offset and the actual count, then the elements.
extern "C" __attribute__((ms_abi)) std::uint32_t cr32_NdrVaryingArraySize(
    std::uint32_t count, std::uint32_t element_size) noexcept {
    const std::size_t after_words =
        ndr_align(8, element_size == 0 ? 1 : element_size);
    return static_cast<std::uint32_t>(after_words + count * element_size);
}

// The packing of a conformant array of bytes.
extern "C" __attribute__((ms_abi)) std::int32_t cr32_NdrMarshalByteArray(
    std::uint8_t* buffer, std::uint32_t capacity, const std::uint8_t* data,
    std::uint32_t count, std::uint32_t* written) noexcept {
    if (buffer == nullptr) {
        return kRpcSInvalidArg;
    }
    const std::uint32_t need = cr32_NdrConformantArraySize(count, 1);
    if (capacity < need) {
        return kRpcSBufferTooSmall;
    }
    write_le32(buffer, count);
    const std::size_t at = ndr_align(4, 1);
    if (data != nullptr && count != 0) {
        std::memcpy(buffer + at, data, count);
    }
    if (written != nullptr) {
        *written = need;
    }
    return ok();
}

// The unmarshalling: the count is read back and the elements follow it.
extern "C" __attribute__((ms_abi)) std::int32_t cr32_NdrUnmarshalByteArray(
    const std::uint8_t* buffer, std::uint32_t length, std::uint8_t* data,
    std::uint32_t capacity, std::uint32_t* count) noexcept {
    if (buffer == nullptr || length < 4) {
        return kRpcSInvalidArg;
    }
    const std::uint32_t elements = read_le32(buffer);
    const std::size_t at = ndr_align(4, 1);
    if (count != nullptr) {
        *count = elements;
    }
    if (data != nullptr) {
        if (capacity < elements || at + elements > length) {
            return kRpcSBufferTooSmall;
        }
        std::memcpy(data, buffer + at, elements);
    }
    return ok();
}

extern "C" __attribute__((ms_abi)) void cr32_NdrWriteInt32(
    std::uint8_t* buffer, std::uint32_t value) noexcept {
    if (buffer != nullptr) {
        write_le32(buffer, value);
    }
}

extern "C" __attribute__((ms_abi)) std::uint32_t cr32_NdrReadInt32(
    const std::uint8_t* buffer) noexcept {
    return buffer == nullptr ? 0 : read_le32(buffer);
}

extern "C" __attribute__((ms_abi)) void cr32_NdrWriteInt16(
    std::uint8_t* buffer, std::uint16_t value) noexcept {
    if (buffer != nullptr) {
        write_le16(buffer, value);
    }
}

extern "C" __attribute__((ms_abi)) std::uint16_t cr32_NdrReadInt16(
    const std::uint8_t* buffer) noexcept {
    return buffer == nullptr ? 0 : read_le16(buffer);
}

extern "C" __attribute__((ms_abi)) std::uint32_t cr32_NdrPrimitiveSize(
    std::uint8_t format_code) noexcept {
    switch (format_code) {
    case kNdrInt8: return 1;
    case kNdrInt16: return 2;
    case kNdrInt32: return 4;
    case kNdrInt64: return 8;
    default: return 0;
    }
}

// ===========================================================================
// The bindings and the interface registration
// ===========================================================================

extern "C" __attribute__((ms_abi)) std::int32_t cr32_RpcStringBindingComposeA(
    std::uint8_t* object_uuid, std::uint8_t* protocol,
    std::uint8_t* network_address, std::uint8_t* endpoint,
    std::uint8_t* options, std::uint8_t** string_binding) noexcept {
    if (string_binding == nullptr) {
        return kRpcSInvalidArg;
    }
    // The binding string the call composes: the parts separated the way
    // the syntax fixes them.
    auto part = [](const std::uint8_t* p) {
        return p == nullptr ? std::string()
                            : std::string(reinterpret_cast<const char*>(p));
    };
    const std::string protocol_text = part(protocol);
    const std::string address = part(network_address);
    const std::string endpoint_text = part(endpoint);
    const std::string options_text = part(options);
    const std::string object = part(object_uuid);
    std::string composed = protocol_text;
    if (!address.empty()) {
        composed += ":" + address;
    }
    if (!endpoint_text.empty()) {
        composed += "[" + endpoint_text + "]";
    }
    if (!options_text.empty()) {
        composed += "," + options_text;
    }
    if (!object.empty()) {
        composed += "," + object;
    }
    if (composed.empty()) {
        return kRpcSInvalidStringBinding;
    }
    auto* buffer = static_cast<std::uint8_t*>(std::malloc(composed.size() + 1));
    if (buffer == nullptr) {
        return kRpcSOutOfMemory;
    }
    std::memcpy(buffer, composed.data(), composed.size() + 1);
    *string_binding = buffer;
    return ok();
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_RpcStringBindingComposeW(
    char16_t* object_uuid, char16_t* protocol, char16_t* network_address,
    char16_t* endpoint, char16_t* options, char16_t** string_binding) noexcept {
    if (string_binding == nullptr) {
        return kRpcSInvalidArg;
    }
    // The wide form: the parts converted and composed the same way.
    auto narrow = [](char16_t* text) {
        std::string out;
        if (text != nullptr) {
            static_cast<void>(utf16_to_utf8(text, out));
        }
        return out;
    };
    const std::string protocol_text = narrow(protocol);
    const std::string address = narrow(network_address);
    const std::string endpoint_text = narrow(endpoint);
    const std::string options_text = narrow(options);
    const std::string object = narrow(object_uuid);
    std::string composed = protocol_text;
    if (!address.empty()) {
        composed += ":" + address;
    }
    if (!endpoint_text.empty()) {
        composed += "[" + endpoint_text + "]";
    }
    if (!options_text.empty()) {
        composed += "," + options_text;
    }
    if (!object.empty()) {
        composed += "," + object;
    }
    std::u16string wide;
    static_cast<void>(utf8_to_utf16(composed, wide));
    auto* buffer = static_cast<char16_t*>(std::malloc((wide.size() + 1) * 2));
    if (buffer == nullptr) {
        return kRpcSOutOfMemory;
    }
    std::memcpy(buffer, wide.data(), wide.size() * 2);
    buffer[wide.size()] = u'\0';
    *string_binding = buffer;
    return ok();
}

// The parse of a binding string: the parts between the separators, each
// answered in its own allocation.
extern "C" __attribute__((ms_abi)) std::int32_t cr32_RpcStringBindingParseA(
    const std::uint8_t* string_binding, std::uint8_t** object_uuid,
    std::uint8_t** protocol, std::uint8_t** network_address,
    std::uint8_t** endpoint, std::uint8_t** options) noexcept {
    if (string_binding == nullptr) {
        return kRpcSInvalidArg;
    }
    const std::string text(reinterpret_cast<const char*>(string_binding));
    if (text.empty()) {
        return kRpcSInvalidStringBinding;
    }
    auto out_part = [](const std::string& value, std::uint8_t** out) {
        if (out == nullptr) {
            return;
        }
        auto* buffer =
            static_cast<std::uint8_t*>(std::malloc(value.size() + 1));
        if (buffer == nullptr) {
            *out = nullptr;
            return;
        }
        std::memcpy(buffer, value.data(), value.size() + 1);
        *out = buffer;
    };
    // The syntax: `protocol:address[endpoint],options,uuid`.
    std::string protocol_text;
    std::string address;
    std::string endpoint_text;
    std::string options_text;
    std::string object;
    const std::size_t colon = text.find(':');
    protocol_text = colon == std::string::npos ? text : text.substr(0, colon);
    if (colon != std::string::npos) {
        address = text.substr(colon + 1);
    }
    const std::size_t open_bracket = address.find('[');
    if (open_bracket != std::string::npos) {
        const std::size_t close_bracket = address.find(']', open_bracket);
        if (close_bracket != std::string::npos) {
            endpoint_text = address.substr(open_bracket + 1,
                                           close_bracket - open_bracket - 1);
            address = address.substr(0, open_bracket) +
                      address.substr(close_bracket + 1);
        }
    }
    // The two commas that follow the address introduce the options and
    // the object uuid.
    const std::size_t first_comma = address.find(',');
    if (first_comma != std::string::npos) {
        std::string tail = address.substr(first_comma + 1);
        address = address.substr(0, first_comma);
        const std::size_t second_comma = tail.find(',');
        if (second_comma == std::string::npos) {
            options_text = tail;
        } else {
            options_text = tail.substr(0, second_comma);
            object = tail.substr(second_comma + 1);
        }
    }
    out_part(object, object_uuid);
    out_part(protocol_text, protocol);
    out_part(address, network_address);
    out_part(endpoint_text, endpoint);
    out_part(options_text, options);
    return ok();
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_RpcBindingFromStringBindingA(
    const std::uint8_t* string_binding, std::uint64_t* binding) noexcept {
    if (string_binding == nullptr || binding == nullptr) {
        return kRpcSInvalidArg;
    }
    const std::string text(reinterpret_cast<const char*>(string_binding));
    if (text.empty()) {
        return kRpcSInvalidStringBinding;
    }
    RpcState& s = rpc_state();
    const Lock held(s.lock);
    const std::uint64_t handle = s.next_binding++;
    s.bindings.emplace(handle, text);
    *binding = handle;
    return ok();
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_RpcBindingFree(
    std::uint64_t* binding) noexcept {
    if (binding == nullptr) {
        return kRpcSInvalidArg;
    }
    RpcState& s = rpc_state();
    const Lock held(s.lock);
    const auto it = s.bindings.find(*binding);
    if (it == s.bindings.end()) {
        return kRpcSInvalidBinding;
    }
    s.bindings.erase(it);
    *binding = 0;
    return ok();
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_RpcServerRegisterIf(
    void* if_spec) noexcept {
    if (if_spec == nullptr) {
        return kRpcSInvalidIf;
    }
    // The interface specification a server passes names its uuid, which
    // is what the registration is keyed by.
    const auto* spec = static_cast<const std::uint8_t*>(if_spec);
    Uuid uuid;
    std::memcpy(&uuid, spec, sizeof(Uuid));
    RpcState& s = rpc_state();
    const Lock held(s.lock);
    for (const RpcState::Registered& entry : s.interfaces) {
        if (uuid_equal(entry.uuid, uuid)) {
            return kRpcSAlreadyRegistered;
        }
    }
    RpcState::Registered entry;
    entry.uuid = uuid;
    s.interfaces.push_back(entry);
    return ok();
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_RpcServerUnregisterIf(
    void* if_spec, const Uuid* type_uuid, std::uint32_t wait) noexcept {
    (void)type_uuid;
    (void)wait;
    if (if_spec == nullptr) {
        return kRpcSInvalidIf;
    }
    const auto* spec = static_cast<const std::uint8_t*>(if_spec);
    Uuid uuid;
    std::memcpy(&uuid, spec, sizeof(Uuid));
    RpcState& s = rpc_state();
    const Lock held(s.lock);
    for (auto it = s.interfaces.begin(); it != s.interfaces.end(); ++it) {
        if (uuid_equal(it->uuid, uuid)) {
            s.interfaces.erase(it);
            return ok();
        }
    }
    return kRpcSNotRegistered;
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_RpcServerUseProtseqEpA(
    std::uint8_t* protocol, std::uint32_t max_calls, std::uint8_t* endpoint,
    void* security) noexcept {
    (void)max_calls;
    (void)security;
    if (protocol == nullptr || endpoint == nullptr) {
        return kRpcSInvalidArg;
    }
    const std::string protocol_text(reinterpret_cast<const char*>(protocol));
    // The protocols this runtime carries: the local transports, which
    // need no network at all.
    if (protocol_text != "ncacn_ip_tcp" && protocol_text != "ncacn_np" &&
        protocol_text != "ncalrpc" && protocol_text != "ncacn_http") {
        return kRpcSNoProtocolSeqs;
    }
    RpcState& s = rpc_state();
    const Lock held(s.lock);
    RpcState::Registered entry;
    s.interfaces.push_back(entry);
    return ok();
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_RpcServerListen(
    std::uint32_t min_calls, std::uint32_t max_calls,
    std::uint32_t dont_wait) noexcept {
    (void)min_calls;
    (void)max_calls;
    (void)dont_wait;
    RpcState& s = rpc_state();
    const Lock held(s.lock);
    if (s.interfaces.empty()) {
        // A listener with nothing registered is the state the call
        // refuses to start from.
        return kRpcSNoEndpoints;
    }
    s.listening = true;
    return ok();
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_RpcMgmtStopServerListening(
    std::uint64_t binding) noexcept {
    (void)binding;
    RpcState& s = rpc_state();
    const Lock held(s.lock);
    s.listening = false;
    return ok();
}

// The client's call: the stub marshals its request and asks the runtime
// to carry it. There is no server to reach here, and the status is the
// one a client of an absent server reads.
extern "C" __attribute__((ms_abi)) std::int32_t cr32_NdrClientCall2(
    std::uint8_t* format, std::uint64_t binding, ...) noexcept {
    (void)format;
    (void)binding;
    return kRpcSCallFailed;
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_NdrAsyncClientCall(
    std::uint8_t* format, void* async_handle, ...) noexcept {
    (void)format;
    (void)async_handle;
    return kRpcSCallFailed;
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_RpcAsyncInitializeHandle(
    void* handle, std::uint32_t size) noexcept {
    if (handle == nullptr) {
        return kRpcSInvalidArg;
    }
    std::memset(handle, 0, size);
    return ok();
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_RpcAsyncGetCallStatus(
    void* handle) noexcept {
    if (handle == nullptr) {
        return kRpcSInvalidArg;
    }
    // The call's status as the handle holds it: a call that never reached
    // a server has not completed.
    return kRpcSCallFailed;
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_RpcMgmtInqIfIds(
    std::uint64_t binding, void** if_ids) noexcept {
    (void)binding;
    if (if_ids != nullptr) {
        *if_ids = nullptr;
    }
    return kRpcSServerUnavailable;
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_RpcIfIdVectorFree(
    void** vector) noexcept {
    if (vector != nullptr && *vector != nullptr) {
        std::free(*vector);
        *vector = nullptr;
    }
    return ok();
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_RpcBindingInqObject(
    std::uint64_t binding, Uuid* object) noexcept {
    if (object == nullptr) {
        return kRpcSInvalidArg;
    }
    RpcState& s = rpc_state();
    const Lock held(s.lock);
    const auto it = s.bindings.find(binding);
    if (it == s.bindings.end()) {
        return kRpcSInvalidBinding;
    }
    // The object a binding names, which the binding string carries as its
    // last comma's tail.
    *object = Uuid{};
    const std::size_t comma = it->second.rfind(',');
    if (comma != std::string::npos) {
        Uuid parsed;
        if (text_to_uuid(it->second.c_str() + comma + 1,
                         it->second.size() - comma - 1, parsed)) {
            *object = parsed;
        }
    }
    return ok();
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_RpcBindingInqIfIds(
    std::uint64_t binding, void** if_ids) noexcept {
    return cr32_RpcMgmtInqIfIds(binding, if_ids);
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_RpcMgmtIsServerListening(
    std::uint64_t binding) noexcept {
    (void)binding;
    RpcState& s = rpc_state();
    const Lock held(s.lock);
    return s.listening ? ok() : kRpcSServerUnavailable;
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_RpcMgmtWaitServerListen()
    noexcept {
    RpcState& s = rpc_state();
    const Lock held(s.lock);
    // The wait a server's main thread makes; with no listener running,
    // the call reports the state it found.
    return s.listening ? ok() : kRpcSServerUnavailable;
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_RpcMgmtSetCancelTimeout(
    std::int32_t timeout) noexcept {
    (void)timeout;
    return ok();
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_RpcMgmtEnableIdleCleanup()
    noexcept {
    return ok();
}

extern "C" __attribute__((ms_abi)) void* cr32_RpcSsAllocate(
    std::size_t size) noexcept {
    return std::malloc(size == 0 ? 1 : size);
}

extern "C" __attribute__((ms_abi)) void cr32_RpcSsFree(void* block) noexcept {
    std::free(block);
}

extern "C" __attribute__((ms_abi)) void cr32_RpcRaiseException(
    std::int32_t status) noexcept {
    // The status the stub's own error structure carries after the call.
    set_last_error(static_cast<std::uint32_t>(status));
}

extern "C" __attribute__((ms_abi)) std::uint32_t cr32_RpcExceptionFilter(
    std::uint32_t code) noexcept {
    // The filter a stub's handler runs: the runtime's own code continues
    // to the handler, and everything else goes on.
    constexpr std::uint32_t kRpcExceptionCode = 0x000006A6;
    return code == kRpcExceptionCode ? 0 : 1;
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_RpcImpersonateClient(
    void* binding) noexcept {
    (void)binding;
    // The impersonation on the server side: this runtime's identity is
    // the guest's own.
    return ok();
}

extern "C" __attribute__((ms_abi)) std::int32_t cr32_RpcRevertToSelf() noexcept {
    return ok();
}

// ===========================================================================
// The registration
// ===========================================================================

void add_rpcrt4(ExportList& out) {
    const auto e = [&out](const char* name, void* fn) {
        HostExport entry;
        entry.name = name;
        entry.address = reinterpret_cast<std::uint64_t>(fn);
        out.push_back(std::move(entry));
    };
    // The uuids.
    e("UuidCreate", reinterpret_cast<void*>(&cr32_UuidCreate));
    e("UuidCreateSequential",
      reinterpret_cast<void*>(&cr32_UuidCreateSequential));
    e("UuidCreateNil", reinterpret_cast<void*>(&cr32_UuidCreateNil));
    e("UuidIsNil", reinterpret_cast<void*>(&cr32_UuidIsNil));
    e("UuidEqual", reinterpret_cast<void*>(&cr32_UuidEqual));
    e("UuidCompare", reinterpret_cast<void*>(&cr32_UuidCompare));
    e("UuidHash", reinterpret_cast<void*>(&cr32_UuidHash));
    e("UuidFromStringA", reinterpret_cast<void*>(&cr32_UuidFromStringA));
    e("UuidFromStringW", reinterpret_cast<void*>(&cr32_UuidFromStringW));
    e("UuidToStringA", reinterpret_cast<void*>(&cr32_UuidToStringA));
    e("UuidToStringW", reinterpret_cast<void*>(&cr32_UuidToStringW));
    e("UuidToStringBracedA",
      reinterpret_cast<void*>(&cr32_UuidToStringBracedA));
    e("UuidToStringBracedW",
      reinterpret_cast<void*>(&cr32_UuidToStringBracedA));
    e("RpcStringFreeA", reinterpret_cast<void*>(&cr32_RpcStringFreeA));
    e("RpcStringFreeW", reinterpret_cast<void*>(&cr32_RpcStringFreeW));
    // The marshalling primitives.
    e("NdrOleAllocate", reinterpret_cast<void*>(&cr32_NdrOleAllocate));
    e("NdrOleFree", reinterpret_cast<void*>(&cr32_NdrOleFree));
    e("midl_user_allocate", reinterpret_cast<void*>(&cr32_midl_user_allocate));
    e("midl_user_free", reinterpret_cast<void*>(&cr32_midl_user_free));
    e("NdrGetBuffer", reinterpret_cast<void*>(&cr32_NdrGetBuffer));
    e("NdrSendReceive", reinterpret_cast<void*>(&cr32_NdrSendReceive));
    e("NdrFreeBuffer", reinterpret_cast<void*>(&cr32_NdrFreeBuffer));
    e("NdrAlignPointer", reinterpret_cast<void*>(&cr32_NdrAlignPointer));
    e("NdrByteOrder", reinterpret_cast<void*>(&cr32_NdrByteOrder));
    e("NdrConformantArraySize",
      reinterpret_cast<void*>(&cr32_NdrConformantArraySize));
    e("NdrVaryingArraySize",
      reinterpret_cast<void*>(&cr32_NdrVaryingArraySize));
    e("NdrPrimitiveSize", reinterpret_cast<void*>(&cr32_NdrPrimitiveSize));
    e("NdrWriteInt32", reinterpret_cast<void*>(&cr32_NdrWriteInt32));
    e("NdrReadInt32", reinterpret_cast<void*>(&cr32_NdrReadInt32));
    e("NdrWriteInt16", reinterpret_cast<void*>(&cr32_NdrWriteInt16));
    e("NdrReadInt16", reinterpret_cast<void*>(&cr32_NdrReadInt16));
    e("NdrClientCall2", reinterpret_cast<void*>(&cr32_NdrClientCall2));
    e("NdrClientCall3", reinterpret_cast<void*>(&cr32_NdrClientCall2));
    e("NdrAsyncClientCall", reinterpret_cast<void*>(&cr32_NdrAsyncClientCall));
    // The bindings and the interfaces.
    e("RpcStringBindingComposeA",
      reinterpret_cast<void*>(&cr32_RpcStringBindingComposeA));
    e("RpcStringBindingComposeW",
      reinterpret_cast<void*>(&cr32_RpcStringBindingComposeW));
    e("RpcStringBindingParseA",
      reinterpret_cast<void*>(&cr32_RpcStringBindingParseA));
    e("RpcStringBindingParseW",
      reinterpret_cast<void*>(&cr32_RpcStringBindingParseA));
    e("RpcBindingFromStringBindingA",
      reinterpret_cast<void*>(&cr32_RpcBindingFromStringBindingA));
    e("RpcBindingFromStringBindingW",
      reinterpret_cast<void*>(&cr32_RpcBindingFromStringBindingA));
    e("RpcBindingFree", reinterpret_cast<void*>(&cr32_RpcBindingFree));
    e("RpcBindingInqObject",
      reinterpret_cast<void*>(&cr32_RpcBindingInqObject));
    e("RpcBindingInqIfIds", reinterpret_cast<void*>(&cr32_RpcBindingInqIfIds));
    e("RpcServerRegisterIf",
      reinterpret_cast<void*>(&cr32_RpcServerRegisterIf));
    e("RpcServerRegisterIf2",
      reinterpret_cast<void*>(&cr32_RpcServerRegisterIf));
    e("RpcServerRegisterIfEx",
      reinterpret_cast<void*>(&cr32_RpcServerRegisterIf));
    e("RpcServerUnregisterIf",
      reinterpret_cast<void*>(&cr32_RpcServerUnregisterIf));
    e("RpcServerUseProtseqEpA",
      reinterpret_cast<void*>(&cr32_RpcServerUseProtseqEpA));
    e("RpcServerUseProtseqEpW",
      reinterpret_cast<void*>(&cr32_RpcServerUseProtseqEpA));
    e("RpcServerListen", reinterpret_cast<void*>(&cr32_RpcServerListen));
    e("RpcMgmtStopServerListening",
      reinterpret_cast<void*>(&cr32_RpcMgmtStopServerListening));
    e("RpcMgmtInqIfIds", reinterpret_cast<void*>(&cr32_RpcMgmtInqIfIds));
    e("RpcIfIdVectorFree", reinterpret_cast<void*>(&cr32_RpcIfIdVectorFree));
    e("RpcMgmtIsServerListening",
      reinterpret_cast<void*>(&cr32_RpcMgmtIsServerListening));
    e("RpcMgmtWaitServerListen",
      reinterpret_cast<void*>(&cr32_RpcMgmtWaitServerListen));
    e("RpcMgmtSetCancelTimeout",
      reinterpret_cast<void*>(&cr32_RpcMgmtSetCancelTimeout));
    e("RpcMgmtEnableIdleCleanup",
      reinterpret_cast<void*>(&cr32_RpcMgmtEnableIdleCleanup));
    // The asynchronous calls and the exceptions.
    e("RpcAsyncInitializeHandle",
      reinterpret_cast<void*>(&cr32_RpcAsyncInitializeHandle));
    e("RpcAsyncGetCallStatus",
      reinterpret_cast<void*>(&cr32_RpcAsyncGetCallStatus));
    e("RpcSsAllocate", reinterpret_cast<void*>(&cr32_RpcSsAllocate));
    e("RpcSsFree", reinterpret_cast<void*>(&cr32_RpcSsFree));
    e("RpcRaiseException", reinterpret_cast<void*>(&cr32_RpcRaiseException));
    e("RpcExceptionFilter", reinterpret_cast<void*>(&cr32_RpcExceptionFilter));
    e("RpcImpersonateClient",
      reinterpret_cast<void*>(&cr32_RpcImpersonateClient));
    e("RpcRevertToSelf", reinterpret_cast<void*>(&cr32_RpcRevertToSelf));
}

}  // namespace occ::runtime::winabi
